import Footer from "../components/Footer";
import LazyEmbed from "../components/LazyEmbed";
import SiteHeader from "../components/SiteHeader";
import { catalog, collaborations, remixes, site } from "../site-data";

const top=[
  {n:"01",title:"BUST IT",plays:"4.159",platform:"YOUTUBE",embed:"https://www.youtube.com/embed/ki1cUmKv_5Y?rel=0&modestbranding=1"},
  {n:"02",title:"RIDDIM RIOT",plays:"3.893",platform:"SOUNDCLOUD",embed:"https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fallenksmusic%2Friddim-riot&color=%2316e7ff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true&show_artwork=true"},
  {n:"03",title:"DAMAGE REMIX",plays:"3.522",platform:"SOUNDCLOUD",embed:"https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fallenksmusic%2Fvirtual-riot-diesel-damage-allen-ks-remix-feat-shaquille-oneal&color=%237547ff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true&show_artwork=true"},
];

export default function MusicPage(){return <main id="top"><SiteHeader active="musica"/><section className="sub-hero music-hero"><div><span className="eyebrow">CATALOG // SIGNAL ARCHIVE</span><h1>MUSIC</h1><p>Originals, remixes, collaborations and live signals from ALLEN KS.</p></div><div className="sub-orbit"><i/><i/><b>AKS</b></div></section><section className="signal-section music-current"><div className="section-heading"><div><span className="eyebrow">01 // CURRENT SIGNAL</span><h2>BASS SO<br/>HEAVY</h2></div><div className="signal-meta"><p><span>STATUS</span><b className="live-dot">OUT NOW</b></p><p><span>DATE</span><b>22.08.26</b></p></div></div><div className="current-grid"><article className="embed-frame red-frame"><LazyEmbed className="square-embed" src={site.bassSoHeavyEmbed} title="BASS SO HEAVY — ALLEN KS"/></article><div className="current-copy"><span className="eyebrow cyan-text">ACTIVE TRANSMISSION</span><h3>CURRENT<br/>FREQUENCY.</h3><p>El release más reciente ocupa el centro del catálogo. El resto de la discografía queda organizada como archivo navegable sin cargar todos los reproductores a la vez.</p><a className="signal-btn red" href={site.soundcloud} target="_blank" rel="noreferrer">OPEN SOUNDCLOUD ↗</a></div></div></section><section className="signal-section top-signals"><div className="section-heading compact"><div><span className="eyebrow">02 // TOP SIGNALS</span><h2>MOST PLAYED</h2></div></div><div className="top-grid">{top.map(item=><article className="top-card" key={item.n}><div><span>{item.n}</span><b>{item.platform}</b></div><h3>{item.title}</h3><p><strong>{item.plays}</strong> reproducciones</p><LazyEmbed className="square-embed" src={item.embed} title={`${item.title} — ALLEN KS`}/></article>)}</div></section><section className="signal-section archive-zone"><div className="archive-grid"><div><span className="eyebrow">03 // SIGNAL ARCHIVE</span><h2>CATALOG</h2><ol>{catalog.map((track,i)=><li key={track}><span>{String(i+1).padStart(2,"0")}</span><strong>{track}</strong><b>ALLEN KS</b></li>)}</ol></div><div className="archive-side"><section><span className="eyebrow cyan-text">REMIXES</span>{remixes.map((track,i)=><article key={track}><span>R{String(i+1).padStart(2,"0")}</span><strong>{track}</strong></article>)}</section><section><span className="eyebrow violet-text">COLLABORATIONS</span>{collaborations.map((track,i)=><article key={track}><span>C{String(i+1).padStart(2,"0")}</span><strong>{track}</strong></article>)}</section></div></div></section><section className="platform-zone"><a href={site.spotify} target="_blank" rel="noreferrer"><span>01</span><strong>SPOTIFY</strong><b>OPEN ↗</b></a><a href={site.soundcloud} target="_blank" rel="noreferrer"><span>02</span><strong>SOUNDCLOUD</strong><b>OPEN ↗</b></a><a href={site.youtube} target="_blank" rel="noreferrer"><span>03</span><strong>YOUTUBE</strong><b>OPEN ↗</b></a></section><Footer/></main>}
