import LazyEmbed from "../components/LazyEmbed";
import SimpleFooter from "../components/SimpleFooter";
import SiteHeader from "../components/SiteHeader";

const top = [
  { n:"01", title:"BUST IT", plays:"4.159", platform:"YouTube", embed:"https://www.youtube.com/embed/ki1cUmKv_5Y?rel=0&modestbranding=1" },
  { n:"02", title:"RIDDIM RIOT", plays:"3.893", platform:"SoundCloud", embed:"https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fallenksmusic%2Friddim-riot&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true&show_artwork=true" },
  { n:"03", title:"DAMAGE REMIX", plays:"3.522", platform:"SoundCloud", embed:"https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fallenksmusic%2Fvirtual-riot-diesel-damage-allen-ks-remix-feat-shaquille-oneal&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true&show_artwork=true" },
];

export default function MusicaPage(){return <main id="top"><SiteHeader active="musica" /><section className="music-current section-dark"><div className="section-index"><span>01</span><span>CATÁLOGO · ALLEN KS</span></div><h1 className="music-current-title">MÁS ESCUCHADOS</h1><div className="music-topbar"><strong>TOP 10 · ALLEN KS</strong><span>01 / 04</span><div><button aria-label="Anterior">←</button><button aria-label="Siguiente">→</button></div></div><div className="music-public-grid">{top.map(item=><article className="music-public-card" key={item.n}><div className="release-card-head"><span>{item.n}</span><b>{item.title}</b></div><div className="music-play-meta"><strong>{item.plays}</strong><span>reproducciones ·<br />{item.platform}</span></div><LazyEmbed className="square-embed" src={item.embed} title={`${item.title} — ALLEN KS en ${item.platform}`} /></article>)}</div></section><section className="soundcloud-selection section-paper"><div className="selection-copy"><div className="section-index"><span>02</span><span>SELECCIÓN DE SOUNDCLOUD</span></div><h2>REMIXES</h2><p>Versiones y relecturas de otros artistas llevadas al sonido de ALLEN KS.</p></div><div className="selection-box"><span>SOUNDCLOUD</span><strong>REMIXES de ALLEN KS en SoundCloud</strong></div></section><section className="soundcloud-selection section-dark"><div className="selection-copy"><div className="section-index"><span>03</span><span>SELECCIÓN DE SOUNDCLOUD</span></div><h2>COLABORACIONES</h2><p>Producciones compartidas con artistas, crews y sellos de la escena bass.</p></div><div className="selection-box selection-box-dark"><span>SOUNDCLOUD</span><strong>COLABORACIONES de ALLEN KS en SoundCloud</strong></div></section><SimpleFooter /></main>}
